### ISSUE TITLE
Error creating ban rule

### ISSUE THREAD

**Issue by Alydus** [EpicBanItemTeam/EpicBanItem#59]
Error thrown while trying to create a rule: 

Modpack: FTB Revelation 3.4.0 on Minecraft 1.12.2
SpongeForge

Command: /ebi create --all-capture ban-industrial-tnt
Holding: Industrial TNT from Industrial Craft 2 (ID: ic2:te, #4096/2)

```
[19:33:06] [Server thread/ERROR] [epicbanitem]: An error was thrown when trying to add a rule:
java.io.IOException: configurate.typesafe.config.ConfigException$Parse: Reader: 1: Key 'ban-industrial-tnt' may not be followed by token: end of file
        at ninja.leaping.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:146) ~[spongeforge-1.12.2-2838-7.3.0.jar:1.12.2-2838-7.3.0]
        at ninja.leaping.configurate.loader.ConfigurationLoader.load(ConfigurationLoader.java:61) ~[spongeforge-1.12.2-2838-7.3.0.jar:1.12.2-2838-7.3.0]
        at team.ebi.epicbanitem.util.TextUtil.serializeStringToConfigNode(TextUtil.java:204) ~[TextUtil.class:?]
        at team.ebi.epicbanitem.command.CommandCreate.execute(CommandCreate.java:167) [CommandCreate.class:?]
        at team.ebi.epicbanitem.command.AbstractCommand$Help.execute(AbstractCommand.java:318) [AbstractCommand$Help.class:?]
        at org.spongepowered.api.command.args.ChildCommandElementExecutor.execute(ChildCommandElementExecutor.java:255) [ChildCommandElementExecutor.class:1.12.2-2838-7.3.0]
        at org.spongepowered.api.command.spec.CommandSpec.process(CommandSpec.java:388) [CommandSpec.class:1.12.2-2838-7.3.0]
        at org.spongepowered.common.command.SpongeCommandDispatcher.process(SpongeCommandDispatcher.java:355) [SpongeCommandDispatcher.class:1.12.2-2838-7.3.0]
        at org.spongepowered.common.command.SpongeCommandManager.process(SpongeCommandManager.java:360) [SpongeCommandManager.class:1.12.2-2838-7.3.0]
        at net.minecraft.command.ServerCommandManager.func_71556_a(SourceFile:665) [dh.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147361_d(NetHandlerPlayServer.java:962) [pa.class:?]
        at net.minecraft.network.NetHandlerPlayServer.func_147354_a(NetHandlerPlayServer.java:941) [pa.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:37) [la.class:?]
        at net.minecraft.network.play.client.CPacketChatMessage.func_148833_a(SourceFile:9) [la.class:?]
        at org.spongepowered.common.event.tracking.phase.packet.PacketPhaseUtil.onProcessPacket(PacketPhaseUtil.java:219) [PacketPhaseUtil.class:1.12.2-2838-7.3.0]
        at net.minecraft.network.PacketThreadUtil$1.redirect$zlc000$impl$redirectToPhaseTracker(SourceFile:540) [hv$1.class:?]
        at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_282]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_282]
        at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
        at org.spongepowered.common.SpongeImplHooks.onUtilRunTask(SpongeImplHooks.java:310) [SpongeImplHooks.class:1.12.2-2838-7.3.0]
        at net.minecraft.server.MinecraftServer.redirect$zjg000$onRun(MinecraftServer.java:4682) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: configurate.typesafe.config.ConfigException$Parse: Reader: 1: Key 'ban-industrial-tnt' may not be followed by token: end of file
        at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:201) ~[ConfigDocumentParser$ParseContext.class:1.12.2-2838-7.3.0]
        at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseError(ConfigDocumentParser.java:197) ~[ConfigDocumentParser$ParseContext.class:1.12.2-2838-7.3.0]
        at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parseObject(ConfigDocumentParser.java:459) ~[ConfigDocumentParser$ParseContext.class:1.12.2-2838-7.3.0]
        at configurate.typesafe.config.impl.ConfigDocumentParser$ParseContext.parse(ConfigDocumentParser.java:646) ~[ConfigDocumentParser$ParseContext.class:1.12.2-2838-7.3.0]
        at configurate.typesafe.config.impl.ConfigDocumentParser.parse(ConfigDocumentParser.java:14) ~[ConfigDocumentParser.class:1.12.2-2838-7.3.0]
        at configurate.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:260) ~[Parseable.class:1.12.2-2838-7.3.0]
        at configurate.typesafe.config.impl.Parseable.rawParseValue(Parseable.java:248) ~[Parseable.class:1.12.2-2838-7.3.0]
        at configurate.typesafe.config.impl.Parseable.parseValue(Parseable.java:180) ~[Parseable.class:1.12.2-2838-7.3.0]
        at configurate.typesafe.config.impl.Parseable.parseValue(Parseable.java:174) ~[Parseable.class:1.12.2-2838-7.3.0]
        at configurate.typesafe.config.impl.Parseable.parse(Parseable.java:299) ~[Parseable.class:1.12.2-2838-7.3.0]
        at configurate.typesafe.config.ConfigFactory.parseReader(ConfigFactory.java:622) ~[ConfigFactory.class:1.12.2-2838-7.3.0]
        at ninja.leaping.configurate.hocon.HoconConfigurationLoader.loadInternal(HoconConfigurationLoader.java:173) ~[spongeforge-1.12.2-2838-7.3.0.jar:1.12.2-2838-7.3.0]
        at ninja.leaping.configurate.hocon.HoconConfigurationLoader.loadInternal(HoconConfigurationLoader.java:54) ~[spongeforge-1.12.2-2838-7.3.0.jar:1.12.2-2838-7.3.0]
        at ninja.leaping.configurate.loader.AbstractConfigurationLoader.load(AbstractConfigurationLoader.java:137) ~[spongeforge-1.12.2-2838-7.3.0.jar:1.12.2-2838-7.3.0]
        ... 26 more
```

Since the IC2 mod shares a lot of the same IDs for its items/blocks, in this example, ic2:te, I have to try ban them based on NBT, when trying to so, I get this error.

Thanks.

**Comment by ginyai** [comment]
try `/ebi create ban-industrial-tnt --all-capture `

**Comment by Alydus** [comment]
> try `/ebi create ban-industrial-tnt --all-capture `

This did not create the error, but doesn't seem to capture anything that helps ban the industrial TNT in this circumstance. The ban doesn't work.

**Comment by SettingDust** [comment]
If it still exitst in https://ore.spongepowered.org/EpicBanItem/EpicBanItem/versions/1.1.6. reopen it
